[preprocessing]
# a POSIX glob pattern listing the input images (see python `iglob.glob`)
  input_pattern = "/datasets/ricordi/**/*.jpg"
# output dir for blob files
  blob_dir = "/datasets/ricordi_blobs"
