[preprocessing]
  # input directory
  input_dir = "/datasets/ricordi/"
  # output dir for blob files
  blob_dir = "/datasets/ricordi/"

[data_entry]
  # the following are here for future reference, but for now the page template
  # is hard-coded in server.py, so values should change accordingly
annotation_values = {BordoPagina = 0, Cancellatura = 1, Sbavatura = 2, TestoStampato = 3, TestoScritto = 4, Pausa = 5, NotaSingola = 6, NoteMultiple = 7, AccordoSingolo = 8, AccordiMultipli = 9, Alterazione = 10, Chiave = 11, Abbellimento = 12, Dinamiche = 13, Altro = 14}
  # the annotation field that will be updated in the json
  annotation_field = "debug"
  # the number of blobs in the control group
  control_length = 1000
  # how many blobs should pass before one from the control group is picked (on average)
  control_freq = 20
  # port for the app
  port = 1992
  # the name that will be used for the control json
  annotator = "tenca1"
