[preprocessing]
  # input directory
  input_dir = "/datasets/ricordi/"
  # output dir for blob files
  blob_dir = "/datasets/ricordi/"

[data_entry]
  # the annotation field that will be updated in the json
  annotation_field = "debug"
  # the number of blobs in the control group
  control_length = 1000
  # how many blobs should pass before one from the control group is picked (on average)
  control_freq = 20
  # port for the app
  port = 1992
  # the name that will be used for the control json
  annotator = "tenca1"

[data_entry.annotation_values] 
  # the buttons with their annotation value
  "Bordo Pagina"= 0
  Cancellatura = 1
  Sbavatura = 2
  "Testo Stampato" = 3
  "Testo Manoscritto" = 4
  "Pausa (intera o quasi)" = 5
  "Nota Singola (con almeno la testa)" = 6
  "Note Multiple (con almeno la testa)" = 7
  "Accordo Singolo (con almeno le teste)" = 8
  "Accordi Multipli (con almeno le teste)" = 9
  "Alterazione (intera o quasi)" = 10
  "Chiave (intera o quasi)" = 11
  "Abbellimento (intero o quasi)" = 12
  "Più categorie" = 13
  Altro = 14
