[tool.poetry]
name = "omr"
version = "0.1.0"
description = ""
authors = ["Federico <federico.simonetta@unimi.it>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
scikit-image = "^0.17.2"
docopt = "^0.6.2"
joblib = "^0.16.0"
scikit-learn = "^0.23.2"

[tool.poetry.dev-dependencies]
ipython = "^7.16.1"
ipdb = "^0.13.3"
jupyter = "^1.0.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
